### ISSUE TITLE
配置后启动总是找不到IP

### ISSUE THREAD

**Issue by ywx332713** [houko/SpringBootUnity#11]
Caused by: java.net.UnknownHostException: ip
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:188)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298)
	... 57 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:50286', transport: 'socket'

**Comment by ywx332713** [comment]
已解决 ：windows 系统中C:\Windows\System32\drivers\etc  的HOSTS文件中添加127.0.0.1       ip
